name: tests
on:
  pull_request:
  push:
    branches: [ main ]

  schedule:
  - cron: '25 08 * * *'

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: Debug with tmate
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    strategy:
      matrix:
        bats_tag: [
          "default",
          "default-optimized",
          "drupal",
          "laravel-redis",
          "laravel-redis-alpine-optimized",
          "laravel-valkey",
          "laravel-valkey-alpine-optimized",
          "laravel-redis-6",
          "drupal-7",
          "drupal-no-settings"
        ]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Install PHP addon DDEV binary
        run: |
          set -eu -o pipefail
          
          # Get latest successful workflow run with artifacts for PHP addon branch
          RUN_ID=""
          for run_id in $(curl -s --fail "https://api.github.com/repos/rfay/ddev/actions/runs?branch=20250806_rfay_php_addon&per_page=5" | jq -r '.workflow_runs[] | select(.conclusion=="success") | .id'); do
            ARTIFACT_COUNT=$(curl -s --fail "https://api.github.com/repos/rfay/ddev/actions/runs/$run_id/artifacts" | jq '.total_count')
            if [ "$ARTIFACT_COUNT" -gt 0 ]; then
              RUN_ID=$run_id
              break
            fi
          done
          echo "Latest run ID with artifacts: $RUN_ID"
          
          # Get ddev-linux-amd64 artifact ID from the run
          ARTIFACT_ID=$(curl -s --fail "https://api.github.com/repos/rfay/ddev/actions/runs/$RUN_ID/artifacts" | jq -r '.artifacts[] | select(.name=="ddev-linux-amd64") | .id')
          echo "Artifact ID: $ARTIFACT_ID"
          
          if [ -z "$ARTIFACT_ID" ] || [ "$ARTIFACT_ID" = "null" ]; then
            echo "ERROR: Could not find ddev-linux-amd64 artifact"
            exit 1
          fi
          
          # Download and install PHP addon DDEV binary
          DOWNLOAD_URL="https://nightly.link/rfay/ddev/actions/artifacts/$ARTIFACT_ID.zip"
          echo "Downloading from: $DOWNLOAD_URL"
          curl -sSL --fail "$DOWNLOAD_URL" -o ddev-php-addon.zip
          unzip -q ddev-php-addon.zip
          sudo cp ddev /usr/local/bin/ddev
          sudo chmod +x /usr/local/bin/ddev
          echo "Installed DDEV version:"
          ddev --version

      - uses: ddev/github-action-add-on-test@v2
        with:
          ddev_version: "stable"
          token: ${{ secrets.GITHUB_TOKEN }}
          debug_enabled: ${{ github.event.inputs.debug_enabled }}
          addon_repository: ${{ env.GITHUB_REPOSITORY }}
          addon_ref: ${{ env.GITHUB_REF }}
          test_command: bats tests --filter-tags ${{ matrix.bats_tag }}
        env:
          PATH: /usr/local/bin:/snap/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
