name: tests
on:
  pull_request:
  push:
    branches: [ main ]

  schedule:
  - cron: '25 08 * * *'

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: Debug with tmate
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    strategy:
      matrix:
        bats_tag: [
          "default",
          "default-optimized",
          "drupal",
          "laravel-redis",
          "laravel-redis-alpine-optimized",
          "laravel-valkey",
          "laravel-valkey-alpine-optimized",
          "laravel-redis-6",
          "drupal-7",
          "drupal-no-settings"
        ]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install DDEV from PHP addon branch
        run: |
          # Install prerequisites
          sudo apt-get update && sudo apt-get install -y curl build-essential
          
          # Clone DDEV from the PHP addon branch
          git clone -b 20250806_rfay_php_addon https://github.com/rfay/ddev.git /tmp/ddev-source
          cd /tmp/ddev-source
          
          # Build and install DDEV
          make clean
          make 
          sudo cp .gotmp/bin/linux_amd64/ddev /usr/local/bin/
          ddev version

      - name: Install bats
        run: |
          sudo apt-get install -y bats

      - name: Run tests
        run: |
          bats tests --filter-tags ${{ matrix.bats_tag }}
