name: tests
on:
  pull_request:
  push:
    branches: [ main ]

  schedule:
  - cron: '25 08 * * *'

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: Debug with tmate
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    strategy:
      matrix:
        bats_tag: [
          "drupal"
        ]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Install PHP addon DDEV binary
        run: |
          # Download and install PHP addon DDEV binary
          curl -sSL https://nightly.link/rfay/ddev/actions/artifacts/3709968561.zip -o ddev-php-addon.zip
          unzip -q ddev-php-addon.zip
          sudo cp ddev /usr/local/bin/ddev
          sudo chmod +x /usr/local/bin/ddev
          echo "Installed DDEV version:"
          ddev --version

      - uses: ddev/github-action-add-on-test@v2
        with:
          ddev_version: "stable"
          token: ${{ secrets.GITHUB_TOKEN }}
          debug_enabled: ${{ github.event.inputs.debug_enabled }}
          addon_repository: ${{ env.GITHUB_REPOSITORY }}
          addon_ref: ${{ env.GITHUB_REF }}
          # test_command: bats tests --filter-tags ${{ matrix.bats_tag }}
          test_command: (brew uninstall -f ddev) && ddev --version
